---
title: "DASC-1104-Proj-Proposal"
author: "Jacob Haarala"
date: "12/3/2020"
output: html_document
---

<link href="/rmarkdown-libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<script src="/rmarkdown-libs/anchor-sections/anchor-sections.js"></script>


<p><em>I haven’t been able to set up my blog I will try to get that set up by tomorrow and email you the link</em></p>
<pre class="r"><code>nfl_elo &lt;- read_csv(file = here::here(&quot;nfl-elo&quot;, &quot;nfl_elo.csv&quot;))</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   .default = col_logical(),
##   date = col_date(format = &quot;&quot;),
##   season = col_double(),
##   neutral = col_double(),
##   team1 = col_character(),
##   team2 = col_character(),
##   elo1_pre = col_double(),
##   elo2_pre = col_double(),
##   elo_prob1 = col_double(),
##   elo_prob2 = col_double(),
##   elo1_post = col_double(),
##   elo2_post = col_double(),
##   score1 = col_double(),
##   score2 = col_double()
## )</code></pre>
<pre><code>## See spec(...) for full column specifications.</code></pre>
<pre><code>## Warning: 234129 parsing failures.
##  row     col           expected actual                                                                                     file
## 1054 playoff 1/0/T/F/TRUE/FALSE      c &#39;/home/jhaarala/git@github.com:jhaarala23/dasc1104-github-repos.git/nfl-elo/nfl_elo.csv&#39;
## 1115 playoff 1/0/T/F/TRUE/FALSE      c &#39;/home/jhaarala/git@github.com:jhaarala23/dasc1104-github-repos.git/nfl-elo/nfl_elo.csv&#39;
## 1169 playoff 1/0/T/F/TRUE/FALSE      c &#39;/home/jhaarala/git@github.com:jhaarala23/dasc1104-github-repos.git/nfl-elo/nfl_elo.csv&#39;
## 1224 playoff 1/0/T/F/TRUE/FALSE      c &#39;/home/jhaarala/git@github.com:jhaarala23/dasc1104-github-repos.git/nfl-elo/nfl_elo.csv&#39;
## 1280 playoff 1/0/T/F/TRUE/FALSE      c &#39;/home/jhaarala/git@github.com:jhaarala23/dasc1104-github-repos.git/nfl-elo/nfl_elo.csv&#39;
## .... ....... .................. ...... ........................................................................................
## See problems(...) for more details.</code></pre>
<pre class="r"><code>nfl_elo_latest &lt;- read_csv(file = here::here(&quot;nfl-elo&quot;, &quot;nfl_elo_latest.csv&quot;))</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   .default = col_double(),
##   date = col_date(format = &quot;&quot;),
##   playoff = col_character(),
##   team1 = col_character(),
##   team2 = col_character(),
##   qb1 = col_character(),
##   qb2 = col_character()
## )
## See spec(...) for full column specifications.</code></pre>
<pre class="r"><code>glimpse(nfl_elo)</code></pre>
<pre><code>## Observations: 16,810
## Variables: 30
## $ date           &lt;date&gt; 1920-09-26, 1920-10-03, 1920-10-03, 1920-10-03, 1920-…
## $ season         &lt;dbl&gt; 1920, 1920, 1920, 1920, 1920, 1920, 1920, 1920, 1920, …
## $ neutral        &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ playoff        &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ team1          &lt;chr&gt; &quot;RII&quot;, &quot;RCH&quot;, &quot;DAY&quot;, &quot;RII&quot;, &quot;CHI&quot;, &quot;CBD&quot;, &quot;BFF&quot;, &quot;AKR&quot;…
## $ team2          &lt;chr&gt; &quot;STP&quot;, &quot;ABU&quot;, &quot;COL&quot;, &quot;MUN&quot;, &quot;MUT&quot;, &quot;PTQ&quot;, &quot;WBU&quot;, &quot;WHE&quot;…
## $ elo1_pre       &lt;dbl&gt; 1503.947, 1503.420, 1493.002, 1516.108, 1368.333, 1504…
## $ elo2_pre       &lt;dbl&gt; 1300.000, 1300.000, 1504.908, 1478.004, 1300.000, 1300…
## $ elo_prob1      &lt;dbl&gt; 0.8246512, 0.8242121, 0.5758191, 0.6441711, 0.6829856,…
## $ elo_prob2      &lt;dbl&gt; 0.1753488, 0.1757879, 0.4241809, 0.3558289, 0.3170144,…
## $ elo1_post      &lt;dbl&gt; 1516.108, 1510.934, 1515.434, 1542.135, 1386.533, 1516…
## $ elo2_post      &lt;dbl&gt; 1287.838, 1292.486, 1482.475, 1451.977, 1281.800, 1287…
## $ qbelo1_pre     &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ qbelo2_pre     &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ qb1            &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ qb2            &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ qb1_value_pre  &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ qb2_value_pre  &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ qb1_adj        &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ qb2_adj        &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ qbelo_prob1    &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ qbelo_prob2    &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ qb1_game_value &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ qb2_game_value &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ qb1_value_post &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ qb2_value_post &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ qbelo1_post    &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ qbelo2_post    &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ score1         &lt;dbl&gt; 48, 10, 14, 45, 20, 48, 32, 43, 66, 0, 51, 40, 37, 42,…
## $ score2         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 14, 0, 0, 7, 0, 0, 0,…</code></pre>
<pre class="r"><code>glimpse(nfl_elo_latest)</code></pre>
<pre><code>## Observations: 269
## Variables: 30
## $ date           &lt;date&gt; 2020-09-10, 2020-09-13, 2020-09-13, 2020-09-13, 2020-…
## $ season         &lt;dbl&gt; 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, …
## $ neutral        &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ playoff        &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ team1          &lt;chr&gt; &quot;KC&quot;, &quot;JAX&quot;, &quot;CAR&quot;, &quot;BAL&quot;, &quot;BUF&quot;, &quot;MIN&quot;, &quot;DET&quot;, &quot;ATL&quot;,…
## $ team2          &lt;chr&gt; &quot;HOU&quot;, &quot;IND&quot;, &quot;OAK&quot;, &quot;CLE&quot;, &quot;NYJ&quot;, &quot;GB&quot;, &quot;CHI&quot;, &quot;SEA&quot;,…
## $ elo1_pre       &lt;dbl&gt; 1664.847, 1438.503, 1417.736, 1638.431, 1511.355, 1571…
## $ elo2_pre       &lt;dbl&gt; 1527.930, 1482.655, 1437.326, 1440.533, 1458.063, 1582…
## $ elo_prob1      &lt;dbl&gt; 0.7617556, 0.5299664, 0.5649799, 0.8195586, 0.6639485,…
## $ elo_prob2      &lt;dbl&gt; 0.2382444, 0.4700336, 0.4350201, 0.1804414, 0.3360515,…
## $ elo1_post      &lt;dbl&gt; 1676.666, 1457.867, 1399.166, 1649.702, 1526.649, 1543…
## $ elo2_post      &lt;dbl&gt; 1516.111, 1463.290, 1455.895, 1429.262, 1442.769, 1609…
## $ qbelo1_pre     &lt;dbl&gt; 1651.215, 1392.057, 1416.302, 1628.808, 1532.806, 1544…
## $ qbelo2_pre     &lt;dbl&gt; 1497.454, 1518.204, 1461.437, 1499.694, 1451.147, 1555…
## $ qb1            &lt;chr&gt; &quot;Patrick Mahomes&quot;, &quot;Gardner Minshew&quot;, &quot;Teddy Bridgewat…
## $ qb2            &lt;chr&gt; &quot;Deshaun Watson&quot;, &quot;Philip Rivers&quot;, &quot;Derek Carr&quot;, &quot;Bake…
## $ qb1_value_pre  &lt;dbl&gt; 239.69530, 121.75534, 155.17461, 262.05705, 153.17524,…
## $ qb2_value_pre  &lt;dbl&gt; 195.6158, 155.6245, 181.3636, 130.9706, 134.1210, 176.…
## $ qb1_adj        &lt;dbl&gt; 6.9428086, -8.6510635, 11.8543782, 17.7484615, 0.60061…
## $ qb2_adj        &lt;dbl&gt; 3.6326586, 6.9773865, 4.4939299, -3.5942770, 5.1901076…
## $ qbelo_prob1    &lt;dbl&gt; 0.7519609, 0.3520553, 0.5041818, 0.7432960, 0.6547578,…
## $ qbelo_prob2    &lt;dbl&gt; 0.2480391, 0.6479447, 0.4958182, 0.2567040, 0.3452422,…
## $ qb1_game_value &lt;dbl&gt; 250.96437, 216.97903, 221.33934, 363.49393, 380.75142,…
## $ qb2_game_value &lt;dbl&gt; 163.113859, 266.985431, 247.800792, 64.243357, 93.6472…
## $ qb1_value_post &lt;dbl&gt; 240.82220, 131.27771, 161.79108, 272.20074, 175.93286,…
## $ qb2_value_post &lt;dbl&gt; 192.3656, 166.7606, 188.0073, 124.2978, 130.0736, 207.…
## $ qbelo1_post    &lt;dbl&gt; 1663.567, 1420.368, 1400.051, 1645.369, 1548.567, 1519…
## $ qbelo2_post    &lt;dbl&gt; 1485.102, 1489.893, 1477.688, 1483.133, 1435.386, 1580…
## $ score1         &lt;dbl&gt; 34, 27, 30, 38, 27, 34, 23, 25, 21, 27, 13, 34, 20, 20…
## $ score2         &lt;dbl&gt; 20, 20, 34, 6, 17, 43, 27, 38, 11, 17, 16, 23, 24, 17,…</code></pre>
<p>For this project, I am examining the elo ratings of NFL teams by age dataset contained in the nfl_elo.csv file found on the fivethirtyeight website. The the first data set consists of 16,810 observations (values based off of results of games played and predicitons made for nfl games) of 30 (numbers that indicate the value of teams at certain points adjusting for the value of their quarterback). The changeable variable/value is a combined varaible of values of home and away quarterbacks, which is a factor that tends to range from 1400 to 1600. The changeable code is a factor with 196 levels which represents a three letter code for the country/region. The changeable year is a separate integer (season) that records every year NFL football has been played. The (other changable variable) elo1 and elo2 is a separate ordered factor with 3 levels that groups the preseason, regular season, and post season. The changeable scores records the scores from different games which also effects the teams’ ratings. Initial exploring things shows that the largest (quality of rating over time or at different points in time) in the elo ratings happens across NFL seasons with the largest number of ratings happening for teams with a quarterback-adjusted elo rating above the average of 1500.</p>
<p>The second dataset used, nfl_elo_latest.csv, has an identical setup for its data to nfl_elo.csv. The only difference is that this dataset has 269 observstions of 30, as opposed to 16,810. This is because as the name indicates it includes only the latest data for all the NFL teams. This means there is less data to choose from, but all the data is relevant to the current day landscape of the NBA.</p>
<p>-Question 1: What is the contending team with the worst qb elo rating, and how does that effect their rating of quality over time.</p>
<p>-Question 2: How does qb elo rating vary from pre to regular to post season?</p>
<p>-Question 3: What teams have consistently high qb elo ratings, and how does that effect their rating of quality over time.</p>
<pre class="r"><code>RAPTOR_byplayer_hist &lt;- read_csv(here::here(&quot;nba-raptor&quot;, &quot;historical_RAPTOR_by_player.csv&quot;))</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   player_name = col_character(),
##   player_id = col_character(),
##   season = col_double(),
##   poss = col_double(),
##   mp = col_double(),
##   raptor_offense = col_double(),
##   raptor_defense = col_double(),
##   raptor_total = col_double(),
##   war_total = col_double(),
##   war_reg_season = col_double(),
##   war_playoffs = col_double(),
##   predator_offense = col_double(),
##   predator_defense = col_double(),
##   predator_total = col_double(),
##   pace_impact = col_double()
## )</code></pre>
<pre class="r"><code>RAPTOR_byteam_hist &lt;- read_csv(here::here(&quot;nba-raptor&quot;, &quot;historical_RAPTOR_by_team.csv&quot;))</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   player_name = col_character(),
##   player_id = col_character(),
##   season = col_double(),
##   season_type = col_character(),
##   team = col_character(),
##   poss = col_double(),
##   mp = col_double(),
##   raptor_offense = col_double(),
##   raptor_defense = col_double(),
##   raptor_total = col_double(),
##   war_total = col_double(),
##   war_reg_season = col_double(),
##   war_playoffs = col_double(),
##   predator_offense = col_double(),
##   predator_defense = col_double(),
##   predator_total = col_double(),
##   pace_impact = col_double()
## )</code></pre>
<pre class="r"><code>RAPTOR_byplayer_latest &lt;- read_csv(here::here(&quot;nba-raptor&quot;, &quot;latest_RAPTOR_by_player.csv&quot;))</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   .default = col_double(),
##   player_name = col_character(),
##   player_id = col_character()
## )</code></pre>
<pre><code>## See spec(...) for full column specifications.</code></pre>
<pre class="r"><code>RAPTOR_byteam_latest &lt;- read_csv(here::here(&quot;nba-raptor&quot;, &quot;latest_RAPTOR_by_team.csv&quot;))</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   .default = col_double(),
##   player_name = col_character(),
##   player_id = col_character(),
##   season_type = col_character(),
##   team = col_character()
## )
## See spec(...) for full column specifications.</code></pre>
<pre class="r"><code>glimpse(RAPTOR_byplayer_hist)</code></pre>
<pre><code>## Observations: 17,483
## Variables: 15
## $ player_name      &lt;chr&gt; &quot;Alaa Abdelnaby&quot;, &quot;Alaa Abdelnaby&quot;, &quot;Alaa Abdelnaby&quot;…
## $ player_id        &lt;chr&gt; &quot;abdelal01&quot;, &quot;abdelal01&quot;, &quot;abdelal01&quot;, &quot;abdelal01&quot;, …
## $ season           &lt;dbl&gt; 1991, 1992, 1993, 1994, 1995, 1977, 1978, 1979, 1980…
## $ poss             &lt;dbl&gt; 640, 1998, 2754, 320, 984, 7674, 5343, 7826, 8226, 6…
## $ mp               &lt;dbl&gt; 303, 959, 1379, 159, 506, 3483, 2399, 3524, 3761, 31…
## $ raptor_offense   &lt;dbl&gt; -3.9384496, -2.5538493, -2.3737358, -6.1400565, -3.8…
## $ raptor_defense   &lt;dbl&gt; -0.5100764, -0.1979430, -2.0698079, -2.7483120, -1.2…
## $ raptor_total     &lt;dbl&gt; -4.4485260, -2.7517923, -4.4435438, -8.8883685, -5.1…
## $ war_total        &lt;dbl&gt; -0.265191008, -0.006892965, -1.227189351, -0.5006002…
## $ war_reg_season   &lt;dbl&gt; -0.22616282, 0.07032163, -0.84527175, -0.50060028, -…
## $ war_playoffs     &lt;dbl&gt; -0.03902819, -0.07721460, -0.38191760, 0.00000000, 0…
## $ predator_offense &lt;dbl&gt; -3.9057318, -2.4995759, -2.3281441, -5.8209360, -3.7…
## $ predator_defense &lt;dbl&gt; -1.69679605, -0.72187632, -2.00226282, -3.52656004, …
## $ predator_total   &lt;dbl&gt; -5.6025279, -3.2214523, -4.3304069, -9.3474961, -4.7…
## $ pace_impact      &lt;dbl&gt; 0.19924063, 0.48543621, 0.48826592, 0.51115221, 1.54…</code></pre>
<pre class="r"><code>glimpse(RAPTOR_byplayer_latest)</code></pre>
<pre><code>## Observations: 530
## Variables: 21
## $ player_name          &lt;chr&gt; &quot;Jaylen Adams&quot;, &quot;Steven Adams&quot;, &quot;Bam Adebayo&quot;, &quot;…
## $ player_id            &lt;chr&gt; &quot;adamsja01&quot;, &quot;adamsst01&quot;, &quot;adebaba01&quot;, &quot;aldrila0…
## $ season               &lt;dbl&gt; 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, …
## $ poss                 &lt;dbl&gt; 43, 3964, 6336, 3648, 31, 1288, 1578, 4197, 252,…
## $ mp                   &lt;dbl&gt; 21, 1890, 3104, 1754, 13, 591, 718, 1984, 117, 3…
## $ raptor_box_offense   &lt;dbl&gt; 2.0231403, 0.3825434, -0.9479613, -0.5268696, -3…
## $ raptor_box_defense   &lt;dbl&gt; 4.19800473, 1.90452101, 2.33824732, 1.08096656, …
## $ raptor_box_total     &lt;dbl&gt; 6.2211451, 2.2870644, 1.3902860, 0.5540970, -9.2…
## $ raptor_onoff_offense &lt;dbl&gt; 21.09359108, -0.08952358, 3.56656133, -0.8248191…
## $ raptor_onoff_defense &lt;dbl&gt; 19.3538834, 0.2474047, 1.2444605, -0.8843753, 5.…
## $ raptor_onoff_total   &lt;dbl&gt; 40.4474745, 0.1578811, 4.8110218, -1.7091945, -8…
## $ raptor_offense       &lt;dbl&gt; 6.20769034, 0.31579672, -0.10394862, -0.66043982…
## $ raptor_defense       &lt;dbl&gt; 7.6562980, 1.6574080, 2.2266522, 0.7770190, -3.6…
## $ raptor_total         &lt;dbl&gt; 13.8639883, 1.9732047, 2.1227036, 0.1165792, -9.…
## $ war_total            &lt;dbl&gt; 0.18028882, 4.54277468, 7.75591619, 2.53091737, …
## $ war_reg_season       &lt;dbl&gt; 0.00000000, 4.32982299, 5.31119544, 2.53091737, …
## $ war_playoffs         &lt;dbl&gt; 0.18028882, 0.21295169, 2.44472074, 0.00000000, …
## $ predator_offense     &lt;dbl&gt; 3.98969773, -0.45857474, 0.72264502, -0.71166820…
## $ predator_defense     &lt;dbl&gt; 3.5119230, 1.6328393, 1.4803914, 1.2298845, -4.9…
## $ predator_total       &lt;dbl&gt; 7.5016208, 1.1742645, 2.2030364, 0.5182163, -7.6…
## $ pace_impact          &lt;dbl&gt; -1.78496720, -0.44522445, -0.64909472, -1.367529…</code></pre>
<pre class="r"><code>glimpse(RAPTOR_byteam_hist)</code></pre>
<pre><code>## Observations: 27,371
## Variables: 17
## $ player_name      &lt;chr&gt; &quot;Alaa Abdelnaby&quot;, &quot;Alaa Abdelnaby&quot;, &quot;Alaa Abdelnaby&quot;…
## $ player_id        &lt;chr&gt; &quot;abdelal01&quot;, &quot;abdelal01&quot;, &quot;abdelal01&quot;, &quot;abdelal01&quot;, …
## $ season           &lt;dbl&gt; 1991, 1991, 1992, 1992, 1993, 1993, 1993, 1994, 1995…
## $ season_type      &lt;chr&gt; &quot;PO&quot;, &quot;RS&quot;, &quot;PO&quot;, &quot;RS&quot;, &quot;PO&quot;, &quot;RS&quot;, &quot;RS&quot;, &quot;RS&quot;, &quot;RS&quot;…
## $ team             &lt;chr&gt; &quot;POR&quot;, &quot;POR&quot;, &quot;POR&quot;, &quot;POR&quot;, &quot;BOS&quot;, &quot;MIL&quot;, &quot;BOS&quot;, &quot;BO…
## $ poss             &lt;dbl&gt; 26, 614, 50, 1948, 128, 322, 2304, 320, 926, 58, 102…
## $ mp               &lt;dbl&gt; 13, 290, 25, 934, 68, 159, 1152, 159, 476, 30, 467, …
## $ raptor_offense   &lt;dbl&gt; -6.5655561, -3.8272040, -5.4308384, -2.4800046, -9.7…
## $ raptor_defense   &lt;dbl&gt; -1.9996253, -0.4470010, -3.1128619, -0.1231248, -3.5…
## $ raptor_total     &lt;dbl&gt; -8.5651814, -4.2742051, -8.5437003, -2.6031294, -13.…
## $ war_total        &lt;dbl&gt; -0.03902819, -0.22616282, -0.07721460, 0.07032163, -…
## $ war_reg_season   &lt;dbl&gt; 0.00000000, -0.22616282, 0.00000000, 0.07032163, 0.0…
## $ war_playoffs     &lt;dbl&gt; -0.03902819, 0.00000000, -0.07721460, 0.00000000, -0…
## $ predator_offense &lt;dbl&gt; -6.9664367, -3.7761254, -5.7222694, -2.4168579, -9.4…
## $ predator_defense &lt;dbl&gt; -4.17002116, -1.59206665, -4.14457738, -0.63402465, …
## $ predator_total   &lt;dbl&gt; -11.1364579, -5.3681921, -9.8668468, -3.0508826, -13…
## $ pace_impact      &lt;dbl&gt; -1.78524722, 0.28327432, 1.21664306, 0.46666807, 0.4…</code></pre>
<pre class="r"><code>glimpse(RAPTOR_byteam_latest)</code></pre>
<pre><code>## Observations: 808
## Variables: 23
## $ player_name          &lt;chr&gt; &quot;Jaylen Adams&quot;, &quot;Steven Adams&quot;, &quot;Steven Adams&quot;, …
## $ player_id            &lt;chr&gt; &quot;adamsja01&quot;, &quot;adamsst01&quot;, &quot;adamsst01&quot;, &quot;adebaba0…
## $ season               &lt;dbl&gt; 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, …
## $ season_type          &lt;chr&gt; &quot;PO&quot;, &quot;PO&quot;, &quot;RS&quot;, &quot;PO&quot;, &quot;RS&quot;, &quot;RS&quot;, &quot;RS&quot;, &quot;RS&quot;, …
## $ team                 &lt;chr&gt; &quot;POR&quot;, &quot;OKC&quot;, &quot;OKC&quot;, &quot;MIA&quot;, &quot;MIA&quot;, &quot;SAS&quot;, &quot;MIA&quot;,…
## $ poss                 &lt;dbl&gt; 43, 442, 3522, 1383, 4953, 3648, 31, 1288, 1578,…
## $ mp                   &lt;dbl&gt; 21, 210, 1680, 687, 2417, 1754, 13, 591, 718, 13…
## $ raptor_box_offense   &lt;dbl&gt; 2.0231403, -0.9363903, 0.5480655, 0.4549766, -1.…
## $ raptor_box_defense   &lt;dbl&gt; 4.19800473, 3.19804930, 1.74218724, 2.34091036, …
## $ raptor_box_total     &lt;dbl&gt; 6.2211451, 2.2616590, 2.2902527, 2.7958870, 0.99…
## $ raptor_onoff_offense &lt;dbl&gt; 21.0935911, -8.4450755, 0.9590721, 5.8354788, 2.…
## $ raptor_onoff_defense &lt;dbl&gt; 19.353883437, -5.085708800, 0.916693782, 2.59976…
## $ raptor_onoff_total   &lt;dbl&gt; 40.4474745, -13.5307843, 1.8757659, 8.4352404, 3…
## $ raptor_offense       &lt;dbl&gt; 6.20769034, -2.44639677, 0.66244338, 1.53300356,…
## $ raptor_defense       &lt;dbl&gt; 7.6562980, 1.6353479, 1.6601764, 2.5051222, 2.14…
## $ raptor_total         &lt;dbl&gt; 13.8639883, -0.8110489, 2.3226198, 4.0381258, 1.…
## $ war_total            &lt;dbl&gt; 0.18028882, 0.21295169, 4.32982299, 2.44472074, …
## $ war_reg_season       &lt;dbl&gt; 0.00000000, 0.00000000, 4.32982299, 0.00000000, …
## $ war_playoffs         &lt;dbl&gt; 0.18028882, 0.21295169, 0.00000000, 2.44472074, …
## $ predator_offense     &lt;dbl&gt; 3.98969773, -4.50971346, 0.04983052, 4.63027747,…
## $ predator_defense     &lt;dbl&gt; 3.5119230, -0.8834823, 1.9486297, 1.8861909, 1.3…
## $ predator_total       &lt;dbl&gt; 7.5016208, -5.3931957, 1.9984603, 6.5164683, 0.9…
## $ pace_impact          &lt;dbl&gt; -1.78496720, -0.60559735, -0.42509815, -0.371700…</code></pre>
<p>Using data I found on GitHub from fivethirtyeight, I will be using raptor data on NBA players that goes all the way back to 2014 to see how accurate it is in projecting the best players. There is four different data sets, two on the team level (historical_RAPTOR_by_team.csv, and latest_RAPTOR_by_team.csv), and two on the individual level (historical_RAPTOR_by_player.csv, and latest_RAPTOR_by_player.csv). I will compare the latest data sets to the latest sets. This will be to see how accurate the historical data is when deciding the validity of the latest data.</p>
<ul>
<li><p>Question 1: Does the pace_impact of a player indicate their impact on the game?</p></li>
<li><p>Question 2: Does the accuracy of the data vary from regular to post season?</p></li>
<li><p>Question 3: What are the trends among the best players for variables like war and variables relating to offense and defense.</p></li>
</ul>
